[package]
name = "suricatax-rule-parser"
version = "0.1.0"
authors = ["Jason Ish <jason@codemonkey.net>"]
edition = "2018"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[workspace]
members = [".", "rjs"]

[features]
default = ["serde_support"]
serde_support = ["serde"]

[dependencies]
nom = "7"
num-traits = "0.2.15"
serde = { version = "1.0.130", default_features = false, features = ["std", "derive"], optional = true }
