[package]
name = "rjs"
version = "0.1.0"
edition = "2021"
authors = ["Jason Ish <jish@oisf.net>"]

[dependencies]
suricata-rule-parser = { path = ".." }
clap = { version = "3.0.0-beta.5", features = ["derive"] }
serde = "1.0.130"
serde_yaml = "0.8.21"
serde_json = "1.0.69"
